blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/GDSC-SWU/2025-Rewear-SolutionChallenge/issues/new?template=feature_request.md
    about: Suggest a new feature for the project
